version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_VOLUME_PATH}:/db/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
